### ISSUE TITLE
关于 initial-scale 布局的问题

### ISSUE THREAD

**Issue by riskers** [ufologist/responsive-page#1]
README中的[initial-scale](http://ufologist.github.io/responsive-page/others-responsive/70c-initial-scale.html)布局应该是生成 `viewport` 脚本有问题。
1. 生成 `viewport` 的代码应该在所有代码执行之前执行，应该放在 `<head>` 里，而且要 document.write 出来
2. 必须要加 `target-densitydpi=device-dpi` ，为了兼容低版本
3. 而且要分版本，就像这样，否则有的手机不识别

```
    if(/Android (\d+\.\d+)/.test(navigator.userAgent)){
        var version = parseFloat(RegExp.$1);
        if(version>2.3){
            var phoneScale = parseInt(window.screen.width)/720;
            document.write('<meta name="viewport" content="width=720, minimum-scale = '+ phoneScale +', maximum-scale = '+ phoneScale +', target-densitydpi=device-dpi">');
        }else{
            document.write('<meta name="viewport" content="width=720, target-densitydpi=device-dpi">');
        }
    }else{
        document.write('<meta name="viewport" content="width=720, user-scalable=no, target-densitydpi=device-dpi">');
    }
```

**Comment by riskers** [comment]
忙完之后仔细看了一下源码，原来是给 `.mod-responsive` 设置 `scale` 实现，这样个人感觉不是很好，因为刚进入页面的时候回是原始scale，然后跳到一个 `scale` 上。
可以像我上面给出的那样，直接在 `viewport` 上做文章，这样就省事了。希望考虑一下。

因为最近也在关注这一方面，希望多多交流。 :smile:

**Comment by ufologist** [comment]
@riskers initial-scale 是在做 responsive-page 这个小东西时参考的一些其他适配方案, 放在一起主要是供大家思考用的, 不属于 responsive-page 的 issue.

responsive-page 的实现原来, 还请参考 https://github.com/ufologist/responsive-page#基础原理
