### ISSUE TITLE
某元素如果用position: fixed时不会悬浮

### ISSUE THREAD

**Issue by chenqq86** [ufologist/responsive-page#2]
某元素如果用position: fixed;时不会悬浮

**Comment by ufologist** [comment]
确实存在这个问题, 要绕过这个问题, 请在执行完 responsivePage 后再将 fixed 元素加入到 DOM 中.

``` javascript
responsivePage();

// 在执行完 responsivePage 后添加 fixed 元素到 DOM 中
var div = document.createElement('div');
div.innerHTML = '<a style="position: fixed; top: 5px; left: 5px;" href="">fixed</a>'
document.body.appendChild(div);
```

完整代码, 请参考 [jd-fixed.html](http://ufologist.github.io/responsive-page/demo/jd-fixed.html)

**Comment by ufologist** [comment]
这个问题是由于父级元素的 transform 会导致子元素 fixed 布局失效, 变成 absolute 效果, 请参考[transform下的fixed布局失效问题](http://www.chengfeilong.com/fixed)
