### ISSUE TITLE
IOS9.3.1 safari，向上滑动页面，会自动放大，试了70c和JD例子也是这样

### ISSUE THREAD

**Issue by HiHelenYang** [ufologist/responsive-page#4]

**Comment by HiHelenYang** [comment]
我解决了，一开始是这样写的把responsiveIt()写在resize()方法里
按下面这样写就没问题了
window.addEventListener("onorientationchange" in window ? "orientationchange" : "resize", function() {
        responsiveIt();
    }, false);

**Comment by ufologist** [comment]
感谢你的反馈
